### ISSUE TITLE
performance on mixed dataset or only canard

### ISSUE THREAD

**Issue by yuanzhi-zhu** [Orange-OpenSource/COQAR#6]
Hi there,

Thank you for your new dataset coqar!
I have tried to finetune a t5 small on mixed dataset and canard only. 

The parameters are:
`{
 "learning_rate": 5e-05,
 "batch_size": 16,
 "weight_decay": 0.0,
 "history_size": 3,
 "dropout_rate": 0.1,
 "include_story": true,
 "model_size": "small"
}`
for both cases.

When evaluating, I had on canard:
> coqar: {'BLEU': 0.3281161005656562, 'ROUGE': 0.37902213930470074, 'METEOR': 0.5437872781076998}
canard: {'BLEU': 0.4881608070125186, 'ROUGE': 0.7137786158777933, 'METEOR': 0.7153993624326819}

comparing to mixed dataset:
> coqar: {'BLEU': 0.40389581211520253, 'ROUGE': 0.4279942932021437, 'METEOR': 0.597503882764309}
canard: {'BLEU': 0.4756776761410914, 'ROUGE': 0.7074058007706036, 'METEOR': 0.7075073407988256}

I observed an improvement on coqar but not canard, is this expected?

**Comment by QGBrabant** [comment]
Hi,

Thank you for reporting your results !

We obtained similar scores. Our guess on why we see no improvement on CANARD is that, in CoQAR, reformulation have quite diverse surface forms and the meaning is sometimes slightly different from the original. On the other hand, CANARD reformulations are more straightforward (closer to the original questions, in terms of surface form) and the sense is usually exactly the same as the original. Probably this is why adding CoQAR during training does not help improving the scores on CANARD.
